### (Data handling)
Import raw differentially expressed gene (DEG) file.

Sort by p-value and clean up = **s1data**  
List of all gene names = **s1names**  
Export to CSV.

In [1]:
import numpy as py
import pandas as pd

rawdata = pd.read_csv("DEG_Oligodendrocyte.csv")

s1data = rawdata.sort_values(by="pvalue")
s1data.reset_index(drop=True, inplace=True)
s1data.head()

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,Gm10754,332.579966,-2.665392,0.293724,-9.074493,1.140000e-19,9.500000e-16
1,Pde10a,1318.299502,-3.145598,0.374423,-8.401177,4.420000e-17,1.840000e-13
2,Rgs9,288.621323,-3.502577,0.430568,-8.134782,4.130000e-16,1.140000e-12
3,Npas2,141.655687,-2.820048,0.375861,-7.502900,6.240000e-14,1.300000e-10
4,Gm28905,167.147482,-2.148665,0.307080,-6.997076,2.610000e-12,4.350000e-09

### (Final list of 1218 significant DEGs)
Sort genes by p-value  
Truncate list at p<0.05 threshold = **s2data**  
List of significant gene names = **s2names**  
Export to CSV.

In [16]:
s1names = s1data["Gene"]
#s1names.to_csv("OL_ALLGeneNames.csv", index=False)

s2data = s1data.loc[s1data["pvalue"]<0.05].sort_values(by="log2FoldChange")
s2names = s2data["Gene"]
#s2names.to_csv("OL_sigGeneNames.csv", index=False)

## Metabolic genes of interest
**Ppargc1b**: <span style="color:blue">downregulated</span>  
master regulator of mitochondrial biogenesis, non-oxidative glucose metabolism
promotes FAO enzyme expression

**Pfkp**: <span style="color:blue">downregulated</span>  
phosphofructokinase P  
first rate-limiting step of glycolysis  

**Pfkfb3**: <span style="color:blue">downregulated</span>  
6-phosphofructo-2-kinase/fructose-2,6-biphosphatase 3
positive modulator of glycolysis  
allosteric activator of Pfk

**Aldh1a1**: <span style="color:red">upregulated</span>  
metabolizes toxic aldehydes; acts as antioxidant against UV rad-induced free radicals
cellular response to oxidative stress

**G6pc3**: <span style="color:red">upregulated</span>  
catalytic subunit of G6Pase, final step in gluconeogenesis

**Nrf1**: <span style="color:red">upregulated</span>  
aka Nfe2l1
required for mitochondrial respiration, mtDNA transcription, and mtDNA replication

**Nfe2l3**: <span style="color:red">upregulated</span>  
aka Nrf3
induces glutathione synthesis pathway

**Hif3a**: <span style="color:red">upregulated</span>  
hypoxia-inducible factor 3 alpha  
*dominant-negative* antagonist for pro-glycolysis family members Hif1a and Hif2a

In [17]:
s2data[s2data["Gene"].isin([ "Pfkp","Pfkfb3","G6pc3","Ppargc1b","Aldh1a1","Nrf1","Hif3a","Nfe2l3" ])]

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
65,Ppargc1b,47.837205,-2.118701,0.432257,-4.901486,9.510000e-07,0.000120
554,Pfkfb3,26.573570,-1.269071,0.481804,-2.633999,8.438574e-03,0.135261
982,Pfkp,63.269752,-0.940663,0.444522,-2.116124,3.433430e-02,0.335133
1211,Nrf1,107.290023,0.663819,0.337775,1.965273,4.938269e-02,0.401045
243,Nfe2l3,101.919904,1.655980,0.464606,3.564266,3.648760e-04,0.012595
1175,Aldh1a1,16.666702,1.797484,0.906961,1.981875,4.749325e-02,0.396683
1209,G6pc3,8.094328,1.902183,0.967437,1.966209,4.927448e-02,NaN
1120,Hif3a,2.898070,2.921480,1.443770,2.023509,4.302072e-02,NaN

## FAO and mitochondrial genes
### Enzymes
**Acaca**: <span style="color:red">upregulated</span>  
acetyl-CoA carboxylase 1  
rate-limiting step in fatty acid synthesis -- supporting myelination?  
subject to phosphorylation and allosteric regulation

**Acat2**: <span style="color:blue">downregulated</span>  
acetyl-CoA acetyltransferase 2  
fatty acid beta-oxidation

**Acot7**: <span style="color:red">upregulated</span>  
cytosolic acyl coenzyme A thioester hydrolase  
removes CoA from fatty acyl CoA

**Eci2**: <span style="color:red">upregulated</span>  
enoyl-Coenzyme A delta isomerase 2  
fatty acid beta-oxidation

**Dgat2**: <span style="color:blue">downregulated</span>  
diacylglycerol O-acyltransferase 2  
negative regulation of FAO

**Phyh**: <span style="color:red">upregulated</span>  
phytanoyl-CoA hydroxylase  
fatty acid alpha-oxidation

**Phyhip**
phytanoyl-CoA 2-hydroxylase interacting protein

### Receptors

**Adipor2**: <span style="color:red">upregulated</span>  
adiponectin receptor  
activation mediates fatty acid beta-oxidation, glucose uptake

**Irs2**: <span style="color:red">upregulated</span>  
insulin receptor substrate 2  
positive regulation of fatty acid beta-oxidation

**Cnr1**: <span style="color:blue">downregulated</span>  
cannabinoid receptor 1 (brain)
negative regulation of fatty acid beta-oxidation

**Nr4a1**: <span style="color:blue">downregulated</span>  
aka Nurr77  
nuclear receptor subfamily 4 group A member 1  
protects FAO; knockdown enhances FAS

**Nr4a3**: <span style="color:blue">downregulated</span>  
aka Nor1  
nuclear receptor subfamily 4 group A member 1  
promotes FAO and TCA pyruvate oxidation

### Other
**Plin3**: <span style="color:red">upregulated</span>  
perilipin 3  
lipid droplet-associated protein, mobilization to lysosomal compartment  
negative regulation of fatty acid beta-oxidation

In [18]:
s2data[s2data["Gene"].str.contains("Acat|Acot7|Acaca|Nr4a|Adipor2|Cnr1|Eci2|Irs2|Plin3|Dgat|Phyh")]

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
423,Nr4a3,7.335314,-3.760842,1.295928,-2.902046,3.707342e-03,NaN
239,Nr4a1,14.396835,-2.916338,0.816200,-3.573069,3.528220e-04,1.237985e-02
5,Cnr1,72.413815,-2.836805,0.411009,-6.902048,5.130000e-12,6.130000e-09
1070,Phyhip,8.371778,-1.602857,0.781050,-2.052184,4.015178e-02,NaN
531,Dgat2,27.909154,-1.320839,0.492018,-2.684536,7.263065e-03,1.209622e-01
1053,Acat2,13.713144,-1.284997,0.621808,-2.066549,3.877667e-02,3.560520e-01
1160,Acot7,85.435514,1.229476,0.617330,1.991603,4.641464e-02,3.920035e-01
515,Acaca,258.633737,1.290158,0.475245,2.714723,6.633114e-03,1.135409e-01
529,Adipor2,150.844952,1.602396,0.596045,2.688383,7.179898e-03,1.199961e-01
581,Irs2,24.665032,1.762192,0.677657,2.600417,9.311049e-03,1.429126e-01
1182,Eci2,6.650719,1.766290,0.892766,1.978447,4.787827e-02,NaN
603,Phyh,9.873679,1.854021,0.719876,2.575471,1.001037e-02,NaN
612,Plin3,11.093651,2.233778,0.872376,2.560569,1.045010e-02,1.527845e-01

## Mitochondrial component genes
**Tomm70a**: <span style="color:blue">downregulated</span>  
mitochondrial import receptor subunit TOM70  
translocase of outer mitochondrial membrane (TOM) complex is a multisubunit complex

**Cyp2j12**: <span style="color:red">upregulated</span>  
cytochrome P450 family 2 subfamily J member 12 

**Cyp20a1**: <span style="color:red">upregulated</span>  
cytochrome P450 family 20 subfamily A member 1  
involved in synthesis of cholesterol, steroids and other lipids

**Cyp27a1**: <span style="color:red">upregulated</span>  
cytochrome P450 family 27 subfamily A member 1  
important for cholesterol homeostasis

**Slc25a25**: <span style="color:blue">downregulated</span>  
ATP-Mg2+/Pi inner mitochondrial membrane solute transporter

**Slc25a13**: <span style="color:red">upregulated</span>  
aspartate/glutamate carrier 2  
exchanges aspartate in mitochondrial matrix for cytosolic glutamate

In [19]:
s2data[s2data["Gene"].str.contains("Tomm|Slc25|Cyp")]

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
213,Slc25a25,30.724518,-1.765121,0.472196,-3.738110,0.000185,0.007252
641,Tomm70a,58.200099,-1.153322,0.457364,-2.521672,0.011680,0.163577
469,Cyp27a1,38.495140,1.325319,0.475350,2.788093,0.005302,0.099036
268,Slc25a13,94.728178,1.529612,0.449171,3.405409,0.000661,0.020818
559,Cyp20a1,21.830109,1.550403,0.590163,2.627077,0.008612,0.136911
642,Cyp2j12,50.511929,1.737850,0.689408,2.520786,0.011709,0.163714

## Lipid trafficking

In [20]:
s2data[s2data["Gene"].str.contains("Abc")]

       Gene   baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
719  Abcc12   4.045838       -3.418347  1.422219 -2.403531  0.016238       NaN
888   Abcc8  10.121508       -1.694235  0.774201 -2.188366  0.028643       NaN
718   Abcg1  67.114231        1.092458  0.454504  2.403628  0.016233  0.205651
486   Abca2  84.618698        1.122749  0.407884  2.752621  0.005912  0.106767
143   Abca1  65.817486        2.524523  0.613327  4.116111  0.000039  0.002226
126  Abca8a  37.081687        2.604308  0.618114  4.213317  0.000025  0.001648

## Other interesting genes
**Pde10a**: <span style="color:blue">downregulated</span>  
cAMP-cGMP phosphodiesterase  
mutations to cAMP binding pocket associated with a rare, severe chorea  
doi: 10.1002/ajmg.a.38507

**Gdnf**: <span style="color:blue">downregulated</span>  
glial cell-derived neurotrophic receptor  
GDNF has been explored as a neuroprotective therapeutic in PD and HD

**Myrf**: <span style="color:red">upregulated</span>  
myelin regulatory factor  
regulates expression of key myelin proteins such as PLP1, MBP, MAG, MOG, ...

**Plppr1**: <span style="color:blue">downregulated</span>  
plasticity related / phospholipid phosphatase-related protein type 1  
reduces cell motility and increases cell adhesion for neurites

In [21]:
s2data[s2data["Gene"].isin([ "Pde10a","Gdnf","Myrf","Plppr1" ])]

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
796,Gdnf,1.817139,-4.293654,1.869876,-2.296224,2.166306e-02,NaN
1,Pde10a,1318.299502,-3.145598,0.374423,-8.401177,4.420000e-17,1.840000e-13
558,Plppr1,172.106027,-1.202067,0.457547,-2.627198,8.609114e-03,1.369114e-01
803,Myrf,50.778447,1.451875,0.634848,2.286965,2.219789e-02,2.557676e-01

## Most different genes
Sort genes by magnitude of log2 fold change = **s2rank**

In [22]:
s2rank = s2data.sort_values(by="log2FoldChange")
s2rank.head()

,Gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
267,Rgs14,4.059452,-5.412735,1.589046,-3.406280,0.000659,NaN
302,Gm12860,3.451424,-5.279882,1.613308,-3.272705,0.001065,NaN
303,9230009I02Rik,3.379423,-5.215531,1.594846,-3.270240,0.001075,NaN
431,Fosl2,3.091609,-5.109557,1.770870,-2.885338,0.003910,NaN
429,Spata21,3.186263,-5.096225,1.764929,-2.887496,0.003883,NaN